Repository SKNETWORKS-FAMILY-AICAMP/SKN09-FINAL-1Team, pull requests merged in 2025-06, with the labels that each got.

#121 [Feat] Front UI update (Dark Theme)
  wlm_front/src/App.jsx
  wlm_front/src/pages/admin/admin.module.css
  wlm_front/src/pages/chatbot/chatbot_con/Base.jsx
  wlm_front/src/pages/chatbot/component/ChatArea.jsx
  wlm_front/src/pages/chatbot/component/sideBar.jsx
  wlm_front/src/pages/chatbot/css/ChatArea.module.css
  wlm_front/src/pages/chatbot/css/FilterPanel.module.css
  wlm_front/src/pages/chatbot/css/SideBar.module.css
  wlm_front/src/pages/login/component/forgotpasswordmodal.jsx
  wlm_front/src/pages/login/css/forgotpasswordmodal.css
  wlm_front/src/pages/login/css/login.css
  wlm_front/src/pages/mainpage/css/mainpage.css
  wlm_front/src/pages/mypage/css/MyPage.module.css
  wlm_front/src/pages/mypage/css/PasswordChangeModal.module.css
  wlm_front/src/pages/mypage/css/UserInfo.module.css
  wlm_front/src/pages/notemate/css/ConfirmModal.css
  wlm_front/src/pages/notemate/css/InfoButton.css
  wlm_front/src/pages/notemate/css/ParticipantList.css
  wlm_front/src/pages/notemate/css/TranscriptBox.css
  wlm_front/src/pages/notemate/css/notemate.css
  wlm_front/src/pages/querymate/css/pagination.css
  wlm_front/src/pages/querymate/css/querymate.css
  wlm_front/src/pages/querymate/css/questionList.module.css
  wlm_front/src/pages/querymate/css/questionitem.css
  wlm_front/src/pages/querymate/css/sidebar.module.css
  wlm_front/src/statics/component/header.jsx
  wlm_front/src/statics/css/footer.css
  wlm_front/src/statics/css/header.css
Labels: enhancement

#132 Refac: db_connection_at_notemate_and_add_live_recoding
  model_hosting/extraction/prompt_extraciont.py
  model_hosting/fast_api.py
  package.json
  wlm_front/src/context/AuthContext.jsx
  wlm_front/src/pages/login/component/login.jsx
  wlm_front/src/pages/notemate/component/InfoButton.jsx
  wlm_front/src/pages/notemate/component/ParticipantList.jsx
  wlm_front/src/pages/notemate/component/TranscriptBox.jsx
  wlm_front/src/pages/notemate/component/notemate.jsx
  wlm_front/src/pages/notemate/css/InfoButton.css
  wlm_front/src/pages/notemate/css/ParticipantList.css
  wlm_front/src/pages/notemate/css/TranscriptBox.css
Labels: enhancement

#128 Feat: Dockerfile & requirements.txt
  db_connection_mvc/Dockerfile
  db_connection_mvc/install_docker.sh
  db_connection_mvc/install_python3.sh
  db_connection_mvc/requirements.txt
  model_hosting/Dockerfile
  model_hosting/install_python_ollama.sh
  model_hosting/requirements.txt
  wlm_front/Dockerfile
  wlm_front/install_docker.sh
  wlm_front/nginx.conf
Labels: enhancement

#137 Feat: Create Chatbot Model Component
  wlm_front/src/pages/querymate/querymate.jsx
  wlm_front/src/statics/chat_modal/component/ChatHistory.jsx
  wlm_front/src/statics/chat_modal/component/ChatInput.jsx
  wlm_front/src/statics/chat_modal/component/ChatModal.jsx
  wlm_front/src/statics/chat_modal/component/MessageButton.jsx
  wlm_front/src/statics/chat_modal/css/ChatHistory.module.css
  wlm_front/src/statics/chat_modal/css/ChatInput.module.css
  wlm_front/src/statics/chat_modal/css/ChatModal.module.css
  wlm_front/src/statics/chat_modal/css/MessageButton.module.css
Labels: enhancement

#151 Refac notemate
  model_hosting/extraction/prompt_extraction.py
  model_hosting/fast_api.py
  model_hosting/module/module.py
  wlm_front/nginx.conf
  wlm_front/src/pages/callmate/components/MainContent.jsx
  wlm_front/src/pages/notemate/component/ParticipantList.jsx
  wlm_front/src/pages/notemate/component/TranscriptBox.jsx
  wlm_front/src/pages/notemate/component/notemate.jsx
Labels: Refac

#153 [Feat] Dev chatbot modal
  db_connection_mvc/controllers/email_controller.py
  db_connection_mvc/controllers/query_controller.py
  db_connection_mvc/main.py
  model_hosting/fast_api.py
  model_hosting/main.py
  model_hosting/module/module.py
  qdrant_db/main.py
  wlm_front/nginx.conf
  wlm_front/src/pages/admin/component/UserCreate.jsx
  wlm_front/src/pages/chatbot/component/ChatArea.jsx
  wlm_front/src/pages/chatbot/component/sideBar.jsx
  wlm_front/src/pages/notemate/component/notemate.jsx
  wlm_front/src/pages/querymate/component/QuestionItem.jsx
  wlm_front/src/pages/querymate/component/QuestionList.jsx
  wlm_front/src/statics/chat_modal/component/ChatModal.jsx
Labels: enhancement

#157 Bug notemate call error
  .gitignore
  wlm_front/Dockerfile
  wlm_front/nginx.conf
Labels: bug

#158 Dev call data con db
  db_connection_mvc/controllers/call_controller.py
  db_connection_mvc/controllers/employee_controller.py
  db_connection_mvc/main.py
  db_connection_mvc/models/database.py
  db_connection_mvc/services/call_service.py
  model_hosting/extraction/prompt_extraction.py
  model_hosting/fast_api.py
  model_hosting/module/module.py
  wlm_front/src/pages/callmate/components/MainContent.jsx
Labels: enhancement

#161 [Feat] Account list
  db_connection_mvc/controllers/email_controller.py
  db_connection_mvc/controllers/employee_controller.py
  db_connection_mvc/models/database.py
  db_connection_mvc/services/employee_service.py
  wlm_front/nginx.conf
  wlm_front/src/pages/admin/AdminBase.jsx
  wlm_front/src/pages/notemate/component/ParticipantList.jsx
  wlm_front/src/pages/notemate/component/notemate.jsx
Labels: enhancement

#163 [Bug] display emp_create_dt
  wlm_front/src/pages/admin/component/UserDetail.jsx
Labels: bug

#177 [Feat] Create querymate collection
  model_hosting/fast_api.py
  qdrant_db/qdrant_loader.py
  wlm_front/src/pages/callmate/components/MainContent.jsx
  wlm_front/src/pages/querymate/component/QuestionItem.jsx
Labels: enhancement

#176 Feat: Add move_vectors qdrant_router
  qdrant_db/qdrant_loader.py
  qdrant_db/qdrant_router.py
Labels: enhancement

#179 Feat: callmate rag collection change
  model_hosting/extraction/prompt_extraction.py
  model_hosting/module/module.py
Labels: enhancement

#182 [Feat] title cleaning
  model_hosting/module/module.py
Labels: enhancement

#183 Refac: call_controller.py & readme
  README.md
  db_connection_mvc/controllers/call_controller.py
Labels: Refac
