Repository SKNETWORKS-FAMILY-AICAMP/SKN09-FINAL-1Team, pull requests merged in 2025-05, with the labels that each got.

#9 Feat: add login and mage page front code
  package-lock.json
  wlm_front/index.html
  wlm_front/package-lock.json
  wlm_front/package.json
  wlm_front/public/images/callbot.png
  wlm_front/public/images/chatmate.png
  wlm_front/public/images/claimmate.png
  wlm_front/public/images/notemate.png
  wlm_front/public/images/wlbmate_logo.png
  wlm_front/src/App.jsx
  wlm_front/src/pages/login/component/login.jsx
  wlm_front/src/pages/login/css/login.css
  wlm_front/src/pages/mainpage/component/mainpage.jsx
  wlm_front/src/pages/mainpage/css/call.png
  wlm_front/src/pages/mainpage/css/chat.png
  wlm_front/src/pages/mainpage/css/mainpage.css
  wlm_front/src/pages/mainpage/css/note.png
  wlm_front/src/pages/mainpage/css/query.png
  wlm_front/src/pages/mainpage/css/wlb_logo.png
  wlm_front/src/pages/notemate/component/notemate.jsx
  wlm_front/src/pages/notemate/css/notemate.css
Labels: enhancement

#15 Feat: Ollama Serving
  model_serving/ollama/__pycache__/main.cpython-312.pyc
  model_serving/ollama/data/1.pdf
  model_serving/ollama/main.py
  model_serving/ollama/ollama_serve.ipynb
  wlm_front/package-lock.json
  wlm_front/package.json
  wlm_front/src/App.jsx
  wlm_front/src/pages/chatbot/component/ChatArea.jsx
  wlm_front/src/static/footer.jsx
  wlm_front/src/static/header.jsx
Labels: enhancement

#19 Refac: folder structure change
  model_hosting/__pycache__/fast_api.cpython-312.pyc
  model_hosting/__pycache__/main.cpython-312.pyc
  model_hosting/data/1.pdf
  model_hosting/extraction/__init__.py
  model_hosting/extraction/__pycache__/__init__.cpython-312.pyc
  model_hosting/extraction/__pycache__/pdf_extraction.cpython-312.pyc
  model_hosting/extraction/__pycache__/prompt_extraciont.cpython-312.pyc
  model_hosting/extraction/pdf_extraction.py
  model_hosting/extraction/prompt_extraciont.py
  model_hosting/fast_api.py
  model_hosting/main.py
  model_hosting/ollama_load/__init__.py
  model_hosting/ollama_load/__pycache__/__init__.cpython-312.pyc
  model_hosting/ollama_load/__pycache__/main.cpython-312.pyc
  model_hosting/ollama_load/__pycache__/ollama_hosting.cpython-312.pyc
  model_hosting/ollama_load/data/1.pdf
  model_hosting/ollama_load/ollama_hosting.py
  model_hosting/ollama_load/ollama_serve.ipynb
  model_hosting/test.py
  model_serving/ollama/main.py
Labels: Refac

#22 Feat: add login page and route to chatbot_page
  model_hosting/data/bigdata.pdf
  model_hosting/extraction/pdf_extraction.py
  model_hosting/fast_api.py
  model_hosting/main.py
  model_hosting/test.py
  wlm_front/src/App.jsx
  wlm_front/src/components/ConfirmModal.css
  wlm_front/src/components/ConfirmModal.jsx
  wlm_front/src/components/MicButton.jsx
  wlm_front/src/components/ParticipantList.jsx
  wlm_front/src/components/TranscriptBox.jsx
  wlm_front/src/pages/login/component/login.jsx
  wlm_front/src/pages/login/css/login.css
  wlm_front/src/pages/notemate/component/notemate.jsx
  wlm_front/src/pages/notemate/css/notemate.css
Labels: enhancement

#24 Feat: Implement login/logout state management and routing
  wlm_front/src/App.jsx
  wlm_front/src/context/AuthContext.jsx
  wlm_front/src/pages/login/component/login.jsx
  wlm_front/src/pages/mainpage/component/mainpage.jsx
  wlm_front/src/pages/notemate/component/notemate.jsx
  wlm_front/src/static/footer.jsx
  wlm_front/src/static/header.jsx
  wlm_front/src/statics/component/header.jsx
Labels: enhancement

#25 Refac: page editing in login and main
  model_hosting/__pycache__/fast_api.cpython-312.pyc
  model_hosting/__pycache__/main.cpython-312.pyc
  model_hosting/ollama_load/__pycache__/__init__.cpython-312.pyc
  model_hosting/ollama_load/__pycache__/main.cpython-312.pyc
  model_hosting/ollama_load/__pycache__/ollama_hosting.cpython-312.pyc
  wlm_front/package-lock.json
  wlm_front/src/components/ParticipantList.jsx
  wlm_front/src/pages/chatbot/chatbot_con/Base.jsx
  wlm_front/src/pages/chatbot/chatbot_con/Base.module.css
  wlm_front/src/pages/chatbot/component/ChatArea.jsx
  wlm_front/src/pages/chatbot/css/ChatArea.module.css
  wlm_front/src/pages/notemate/css/notemate.css
Labels: enhancement

#35 Fix: Improve visibility of NoteMate frontend UI
  model_hosting/data/bigdata.pdf
  wlm_front/src/components/ParticipantList.css
  wlm_front/src/components/ParticipantList.jsx
  wlm_front/src/components/TranscriptBox.css
  wlm_front/src/components/TranscriptBox.jsx
  wlm_front/src/pages/chatbot/component/ChatArea.jsx
  wlm_front/src/pages/notemate/component/notemate.jsx
  wlm_front/src/pages/notemate/css/notemate.css
Labels: Refac

#48 [FEAT] UI updates for ChatMate, Header, and NoteMate button
  wlm_front/src/App.jsx
  wlm_front/src/components/MicButton.jsx
  wlm_front/src/pages/chatbot/chatbot_con/Base.jsx
  wlm_front/src/pages/chatbot/chatbot_con/Base.module.css
  wlm_front/src/pages/chatbot/component/sideBar.jsx
  wlm_front/src/pages/chatbot/css/ChatArea.module.css
  wlm_front/src/pages/chatbot/css/FilterPanel.module.css
  wlm_front/src/pages/chatbot/css/SideBar.module.css
  wlm_front/src/pages/images/callbot-dark-light.png
  wlm_front/src/pages/images/callbot-image.png
  wlm_front/src/pages/images/chatbot-dark-light.png
  wlm_front/src/pages/images/chatbot-image.png
  wlm_front/src/pages/images/logo-image2.png
  wlm_front/src/pages/images/notemate-dark-light.png
  wlm_front/src/pages/images/notemate-image.png
  wlm_front/src/pages/images/querymate-dark-light.png
  wlm_front/src/pages/images/querymate-image.png
  wlm_front/src/pages/login/component/login.jsx
  wlm_front/src/pages/login/css/login.css
  wlm_front/src/statics/component/header.jsx
  wlm_front/src/statics/css/footer.css
  wlm_front/src/statics/css/header.css
Labels: enhancement

#50 Feat: add callmate page
  model_hosting/__pycache__/fast_api.cpython-312.pyc
  model_hosting/__pycache__/main.cpython-312.pyc
  model_hosting/data_loader/__pycache__/qdrant_loader.cpython-312.pyc
  model_hosting/extraction/__pycache__/pdf_extraction.cpython-312.pyc
  model_hosting/extraction/__pycache__/prompt_extraciont.cpython-312.pyc
  wlm_front/src/App.jsx
  wlm_front/src/pages/callmate/Callmate.jsx
  wlm_front/src/pages/callmate/components/MainContent.jsx
  wlm_front/src/pages/callmate/components/Sidebar.jsx
  wlm_front/src/pages/callmate/css/Callmate.module.css
  wlm_front/src/pages/callmate/css/MainContent.module.css
  wlm_front/src/pages/callmate/css/Sidebar.module.css
Labels: enhancement

#59 Feat:main UI page
  wlm_front/src/pages/login/css/login.css
  wlm_front/src/pages/mainpage/component/mainpage.jsx
  wlm_front/src/pages/mainpage/css/mainpage.css
  wlm_front/src/pages/notemate/component/notemate.jsx
  wlm_front/src/statics/component/header.jsx
  wlm_front/src/statics/css/header.css
Labels: enhancement

#57 Feat: admin_ui_page
  wlm_front/src/App.jsx
  wlm_front/src/pages/admin/AdminBase.jsx
  wlm_front/src/pages/admin/admin.module.css
  wlm_front/src/pages/admin/component/AdminHeader.jsx
  wlm_front/src/pages/admin/component/AdminMain.jsx
  wlm_front/src/pages/admin/component/AdminSidebar.jsx
  wlm_front/src/pages/admin/component/UserCreate.jsx
  wlm_front/src/pages/admin/component/UserDetail.jsx
  wlm_front/src/pages/admin/component/UserList.jsx
  wlm_front/src/pages/admin/component/UserSearch.jsx
  wlm_front/src/pages/admin/css/AdminSidebar.module.css
  wlm_front/src/pages/admin/css/UserCreate.module.css
  wlm_front/src/pages/admin/css/UserDetail.module.css
  wlm_front/src/pages/admin/css/UserList.module.css
  wlm_front/src/pages/admin/css/UserSearch.module.css
Labels: enhancement

#60 Feat: mypage_ui_front
  wlm_front/src/App.jsx
  wlm_front/src/pages/callmate/Callmate.jsx
  wlm_front/src/pages/callmate/components/MainContent.jsx
  wlm_front/src/pages/callmate/css/MainContent.module.css
  wlm_front/src/pages/mypage/component/MyPage.jsx
  wlm_front/src/pages/mypage/component/PasswordChangeModal.jsx
  wlm_front/src/pages/mypage/component/UserInfo.jsx
  wlm_front/src/pages/mypage/css/MyPage.module.css
  wlm_front/src/pages/mypage/css/PasswordChangeModal.module.css
  wlm_front/src/pages/mypage/css/UserInfo.module.css
Labels: enhancement

#62 Bug: resolve error & delete cache files
  model_hosting/__pycache__/fast_api.cpython-312.pyc
  model_hosting/__pycache__/main.cpython-312.pyc
  model_hosting/data_loader/__pycache__/qdrant_loader.cpython-312.pyc
  model_hosting/extraction/__pycache__/__init__.cpython-312.pyc
  model_hosting/extraction/__pycache__/pdf_extraction.cpython-312.pyc
  model_hosting/extraction/__pycache__/prompt_extraciont.cpython-312.pyc
  model_hosting/ollama_load/__pycache__/__init__.cpython-312.pyc
  model_hosting/ollama_load/__pycache__/ollama_hosting.cpython-312.pyc
  wlm_front/src/App.jsx
Labels: bug

#69 Feat: add db_connection_mvc folders & setting mcv pattern
  db_connection_mvc/controllers/__init__.py
  db_connection_mvc/controllers/employee_controller.py
  db_connection_mvc/main.py
  db_connection_mvc/models/__init__.py
  db_connection_mvc/models/database.py
  db_connection_mvc/services/__init__.py
  db_connection_mvc/services/employee_service.py
Labels: enhancement

#70 [Feat] NoteMate and Header Update
  wlm_front/src/App.jsx
  wlm_front/src/App.module.css
  wlm_front/src/pages/notemate/component/ParticipantList.jsx
  wlm_front/src/pages/notemate/component/TranscriptBox.jsx
  wlm_front/src/pages/notemate/component/notemate.jsx
  wlm_front/src/pages/notemate/css/ParticipantList.css
  wlm_front/src/pages/notemate/css/TranscriptBox.css
  wlm_front/src/pages/notemate/css/notemate.css
  wlm_front/src/statics/component/footer.jsx
  wlm_front/src/statics/component/header.jsx
  wlm_front/src/statics/css/footer.css
  wlm_front/src/statics/css/header.css
Labels: enhancement

#82 Refac: mainpage_ui_update
  model_hosting/data/qdrant_db/.lock
  model_hosting/data/qdrant_db/meta.json
  wlm_front/src/App.jsx
  wlm_front/src/pages/mainpage/component/mainpage.jsx
  wlm_front/src/pages/mainpage/css/call.jpeg
  wlm_front/src/pages/mainpage/css/call2.jpeg
  wlm_front/src/pages/mainpage/css/chat.jpeg
  wlm_front/src/pages/mainpage/css/mainpage.css
  wlm_front/src/pages/mainpage/css/meet.jpeg
  wlm_front/src/pages/mainpage/css/query.jpg
  wlm_front/src/pages/mainpage/css/wlb_logo.png
  wlm_front/src/pages/mainpage/css/wlbmate_logo.png
  wlm_front/src/pages/querymate/component/QuestionList.jsx
  wlm_front/src/pages/querymate/querymate.jsx
Labels: Refac

#85 [Refac]Button & QueryMate Filter Changed
  wlm_front/package-lock.json
  wlm_front/package.json
  wlm_front/src/pages/callmate/css/MainContent.module.css
  wlm_front/src/pages/callmate/css/Sidebar.module.css
  wlm_front/src/pages/chatbot/component/ChatArea.jsx
  wlm_front/src/pages/chatbot/component/sideBar.jsx
  wlm_front/src/pages/chatbot/css/ChatArea.module.css
  wlm_front/src/pages/chatbot/css/SideBar.module.css
  wlm_front/src/pages/notemate/css/ParticipantList.css
  wlm_front/src/pages/notemate/css/TranscriptBox.css
  wlm_front/src/pages/notemate/css/notemate.css
  wlm_front/src/pages/querymate/component/QuestionItem.jsx
  wlm_front/src/pages/querymate/component/QuestionList.jsx
  wlm_front/src/pages/querymate/component/Sidebar.jsx
  wlm_front/src/pages/querymate/css/questionitem.css
  wlm_front/src/pages/querymate/css/sidebar.css
  wlm_front/src/pages/querymate/querymate.jsx
  wlm_front/src/statics/css/header.css
Labels: Refac

#87 [Refac]Solved Status yellow dot issue
  wlm_front/src/pages/querymate/component/QuestionItem.jsx
  wlm_front/src/pages/querymate/component/Sidebar.jsx
  wlm_front/src/pages/querymate/css/questionitem.css
Labels: Refac

#100 Style: Front UI/UX Update
  wlm_front/src/pages/callmate/Callmate.jsx
  wlm_front/src/pages/callmate/components/MainContent.jsx
  wlm_front/src/pages/callmate/components/Sidebar.jsx
  wlm_front/src/pages/callmate/css/MainContent.module.css
  wlm_front/src/pages/callmate/css/Sidebar.module.css
  wlm_front/src/pages/chatbot/component/ChatArea.jsx
  wlm_front/src/pages/chatbot/component/FilterPanel.jsx
  wlm_front/src/pages/chatbot/component/sideBar.jsx
  wlm_front/src/pages/chatbot/css/ChatArea.module.css
  wlm_front/src/pages/chatbot/css/FilterPanel.module.css
  wlm_front/src/pages/chatbot/css/SideBar.module.css
  wlm_front/src/pages/notemate/component/ConfirmModal.jsx
  wlm_front/src/pages/notemate/component/InfoButton.jsx
  wlm_front/src/pages/notemate/component/InfoModal.jsx
  wlm_front/src/pages/notemate/component/MicButton.jsx
  wlm_front/src/pages/notemate/component/ParticipantList.jsx
  wlm_front/src/pages/notemate/component/TranscriptBox.jsx
  wlm_front/src/pages/notemate/component/notemate.jsx
  wlm_front/src/pages/notemate/css/InfoButton.css
  wlm_front/src/pages/notemate/css/InfoModal.css
  wlm_front/src/pages/notemate/css/ParticipantList.css
  wlm_front/src/pages/notemate/css/TranscriptBox.css
  wlm_front/src/pages/notemate/css/notemate.css
  wlm_front/src/pages/querymate/component/QuestionItem.jsx
  wlm_front/src/pages/querymate/component/QuestionList.jsx
  wlm_front/src/pages/querymate/component/Sidebar.jsx
  wlm_front/src/pages/querymate/css/questionList.module.css
  wlm_front/src/pages/querymate/css/questionitem.css
  wlm_front/src/pages/querymate/css/sidebar.css
  wlm_front/src/pages/querymate/css/sidebar.module.css
  wlm_front/src/pages/querymate/querymate.jsx
  wlm_front/src/statics/component/DateSearch.jsx
  wlm_front/src/statics/css/DateSearch.module.css
Labels: bug

#102 Bug: date search conflict
  wlm_front/src/pages/callmate/components/MainContent.jsx
  wlm_front/src/pages/callmate/components/Sidebar.jsx
  wlm_front/src/pages/callmate/css/Sidebar.module.css
  wlm_front/src/pages/chatbot/component/sideBar.jsx
  wlm_front/src/pages/querymate/component/QuestionList.jsx
  wlm_front/src/pages/querymate/component/Sidebar.jsx
  wlm_front/src/pages/querymate/css/sidebar.module.css
  wlm_front/src/statics/component/DateSearch.jsx
  wlm_front/src/statics/css/DateSearch.module.css
Labels: bug, enhancement
